### ISSUE TITLE
EMD value extremely large

### ISSUE THREAD

**Issue by YiruS** [daerduoCarey/PyTorchEMD#4]
Hi,

I wanted to run the EMD, however, the value is extremely large. FOr example, chamfer distance is about 0.07, however, EMD generated from this code is 60-ish. I wonder is there any normalization that we should take care of?

Thanks!

**Comment by daerduoCarey** [comment]
You should divide it by the number of points.

**Comment by YiruS** [comment]
> You should divide it by the number of points.
