### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by zou-longkun** [daerduoCarey/PyTorchEMD#9]
Hi, I have met a problem "RuntimeError: CUDA error: an illegal memory access was encountered" when specified a  gpu device other than device 0. For example, if there are more than one gpu device, I want to specify gpu 2 to train a model.

**Comment by daerduoCarey** [comment]
try CUDA_VISIBLE_DEVICES=2 python train.py
